#!/usr/bin/env sh

: ${VSI_MUSL=-1}

if test "${VSI_MUSL}" -eq -1; then
  if command -v ldd 2>&1 > /dev/null; then
    if ! VSI_MUSL=`ldd --version 2>&1`; then
      # Some versions of ldd fail when using the --version flag, but succeed on
      # no flag
      VSI_MUSL=`ldd 2>&1 || :`
    fi
    # Was musl not found in first line
    if command -v awk 2>&1 > /dev/null; then
      if echo "${VSI_MUSL}" | awk '{if (NR < 2 && $0 ~ /musl/) {exit 1} else {exit 0}}'; then
        VSI_MUSL=0
      else
        VSI_MUSL=1
      fi
    else
      if echo "${VSI_MUSL}" | head -n1 | grep -q musl; then
        VSI_MUSL=1
      else
        VSI_MUSL=0
      fi
    fi
  fi
fi

if test "${VSI_MUSL}" -eq "1"; then
  exec /usr/local/bin/docker-compose_musl ${@+"${@}"}
else
  exec /usr/local/bin/docker-compose_glib ${@+"${@}"}
fi
