version: '2.2'
#If start using multistage docker images
#version: '2.3'

services:
  amanda_deb:
    build:
      context: .
      dockerfile: recipe_amanda_deb.Dockerfile
      # args:
      #   AMANDA_VERSION: "${AMANDA_VERSION}"
    image: vsiri/recipe:amanda_deb

  gosu:
    build:
      context: .
      dockerfile: recipe_gosu.Dockerfile
      # args:
      #   GOSU_VERSION: "${GOSU_VERSION}"
    image: vsiri/recipe:gosu

  tini:
    build:
      context: .
      dockerfile: recipe_tini.Dockerfile
      # args:
      #   TINI_VERSION: "${TINI_VERSION}"
    image: vsiri/recipe:tini

  tini-musl:
    build:
      context: .
      dockerfile: recipe_tini-musl.Dockerfile
      # args:
      #   TINI_VERSION: "${TINI_VERSION}"
    image: vsiri/recipe:tini-musl

  ep:
    build:
      context: .
      dockerfile: recipe_ep.Dockerfile
      # args:
      #   EP_VERSION: "${EP_VERSION}"
    image: vsiri/recipe:ep

  jq:
    build:
      context: .
      dockerfile: recipe_jq.Dockerfile
      # args:
      #   JQ_VERSION: "${JQ_VERSION}"
    image: vsiri/recipe:jq

  ninja:
    build:
      context: .
      dockerfile: recipe_ninja.Dockerfile
    image: vsiri/recipe:ninja

  cmake:
    build:
      context: .
      dockerfile: recipe_cmake.Dockerfile
    image: vsiri/recipe:cmake

  docker:
    build:
      context: .
      dockerfile: recipe_docker.Dockerfile
    image: vsiri/recipe:docker

  git-lfs:
    build:
      context: .
      dockerfile: recipe_git-lfs.Dockerfile
    image: vsiri/recipe:git-lfs

  pipenv:
    build:
      context: .
      dockerfile: recipe_pipenv.Dockerfile
    image: vsiri/recipe:pipenv

  vsi:
    build:
      context: ../..
      dockerfile: docker/recipes/recipe_vsi.Dockerfile
    image: vsiri/recipe:vsi

  onetrueawk:
    build:
      context: .
      dockerfile: recipe_onetrueawk.Dockerfile
      # args:
      #   ONETRUEAWK_VERSION: "${ONETRUEAWK_VERSION}"
    image: vsiri/recipe:onetrueawk