#!/usr/bin/env sh

set -eu

# Useful for creating a fake editable package for when you plan on mounting it
# in at runtime

# $1 - Base directory of the python package (where setup.py goes)
# $2 - Name of the python package
# $3... - Optional module list of the python source code dir, defaults to same as $2

# Make sure the directory exists and cd into it
mkdir -p "${1}"
cd "${1}"
name=${2}

# Keep the name around as one of the dirs to be created, if there are no others
if [ "${#}" = "2" ]; then
  shift 1
else
  shift 2
fi

# Use Autodiscovery: https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#automatic-discovery
if [ ! -e "setup.py" -a ! -e "pyproject.toml" ]; then
  (
    echo "[build-system]"
    echo "requires = [\"setuptools >= 61.0\"]"
    echo "build-backend = 'setuptools.build_meta'"
    echo "[project]"
    echo "version = \"0.0.1\""
    echo "name = \"${name}\""
  ) > pyproject.toml
fi

while (( ${#} )); do
  mkdir -p "${1}"
  touch "${1}/__init__.py"
  shift 1
done
