version: 2
jobs:
  build:
    docker:
      - image: vsiri/circleci:bash-compose-lfs
    environment:
      VSI_COMMON_DIR: /vsi
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Checkout vsi_common
          command: |
            git clone --recursive https://github.com/VisionSystemsInc/vsi_common.git /vsi

      - setup_remote_docker

      - run:
          name: Build recipes
          command: |
            sed 's|context: ../..|context: ${VSI_COMMON_DIR}|' docker-compose.yml
            docker-compose build

      - run:
          name: Run integration tests
          environment:
            TESTS_DIR: /repo/tests
          command: |
            "${VSI_COMMON_DIR}/tests/run_tests.bsh"