#!/usr/bin/env bash

if [ "${DOCKER_TAG}" = "vsi" ]; then
  git clone --recursive https://github.com/visionsystemsinc/vsi_common.git
  cd vsi_common/docker/recipes
  git checkout main
  docker compose build ${DOCKER_TAG}
else
  docker compose build ${DOCKER_TAG}
fi